### ISSUE TITLE
FreeBSD: Can't assign requested address

### ISSUE THREAD

**Issue by xiwenc** [Danielhiversen/PyXiaomiGateway#137]
**Home Assistant release with the issue (if applicable):**

**Last working Home Assistant release (if known):**
unknown

**PyXiaomiGateway library version (if known):**
0.11.1

**Operating environment (Hass.io/Docker/Windows/etc.):**
FreeBSD 11.2-RELEASE-p7  (freenas)

**Traceback (if applicable):**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/xiaomi_aqara.py", line 137, in setup
    xiaomi.listen()
  File "/root/.homeassistant/deps/lib/python3.7/site-packages/xiaomi_gateway/__init__.py", line 138, in listen
    self._mcastsocket = self._create_mcast_socket()
  File "/root/.homeassistant/deps/lib/python3.7/site-packages/xiaomi_gateway/__init__.py", line 119, in _create_mcast_socket
    sock.bind((self.MULTICAST_ADDRESS, self.MULTICAST_PORT))
OSError: [Errno 49] Can't assign requested address
```

The module tries to bind to multicast when it's not Windows:
```
         if self._interface != 'any':
             if platform.system() != "Windows":
                 sock.bind((self.MULTICAST_ADDRESS, self.MULTICAST_PORT))
             else:
                 sock.bind((self._interface, self.MULTICAST_PORT))
```

It seems this breaks (is not available?) on FreeBSD.

**Comment by xiwenc** [comment]
To run in Freebsd jail it's also required to turn on `allow_raw_sockets` if not sensors and the gateway itself are not fully working.

**Comment by xiwenc** [comment]
After more intensive testing it's best to revert https://github.com/Danielhiversen/PyXiaomiGateway/pull/138 because that was not the core issue. It could be breaking something else I'm not aware of instead.

So to summarize the working setup is:
- Run homeassistant with xiaomi gateway as a `11.2-RELEASE-p7` FreeBSD jail on FreeNAS 11.2-stable
- the jail must use `vnet` with option `allow_raw_sockets=1`

related links:
- https://forums.freenas.org/index.php?threads/how-can-i-receive-udp-multicast-packets-in-an-iocage-jail.68960/
- https://community.home-assistant.io/t/pyxiaomigateway-problem-error-invalid-key/28168/80

Sorry for the confusion! Hope this helps others in the future when attempting to run in jails.
